name: Adapters Runtime Testing

on:
  push:
    branches: [main, develop]
    paths:
      - 'packages/adapters/**'
      - '.github/workflows/adapters-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'packages/adapters/**'
      - '.github/workflows/adapters-ci.yml'

jobs:
  # Node.js Adapter Tests
  node-adapter:
    name: Node.js Adapter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build --filter="@plank/adapter-node"

      - name: Run tests
        run: pnpm test --filter="@plank/adapter-node"

      - name: Type check
        run: pnpm type-check --filter="@plank/adapter-node"

      - name: Lint
        run: pnpm lint --filter="@plank/adapter-node"

  # Bun Adapter Tests
  bun-adapter:
    name: Bun Adapter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build --filter="@plank/adapter-bun"

      - name: Run unit tests
        run: pnpm test --filter="@plank/adapter-bun"

      - name: Type check
        run: pnpm type-check --filter="@plank/adapter-bun"

      - name: Lint
        run: pnpm lint --filter="@plank/adapter-bun"

      - name: Test Bun runtime compatibility
        run: |
          echo "Testing Bun adapter with actual Bun runtime..."
          bun -e "
            const adapter = require('./packages/adapters/bun/dist/index.js');
            console.log('✅ Bun adapter loads successfully in Bun runtime');
            console.log('Available exports:', Object.keys(adapter));
            console.log('createBunAdapter type:', typeof adapter.createBunAdapter);

            // Test that we can actually create an adapter instance
            try {
              const testAdapter = adapter.createBunAdapter({ port: 0 });
              console.log('✅ Can create Bun adapter instance');
              console.log('Adapter type:', typeof testAdapter);
            } catch (error) {
              console.log('⚠️  Adapter creation test:', error.message);
            }
          "

      - name: Run Bun integration tests
        run: cd packages/adapters/bun && bun test test-bun.test.js

  # Edge Adapter Tests (Cloudflare Workers)
  edge-adapter:
    name: Edge Adapter (Workers)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build --filter="@plank/adapter-edge"

      - name: Run unit tests (Node.js environment)
        run: pnpm test --filter="@plank/adapter-edge"

      - name: Run Edge integration tests
        run: |
          echo "Running Edge adapter integration tests..."
          cd packages/adapters/edge
          node test-edge.test.js

      - name: Type check
        run: pnpm type-check --filter="@plank/adapter-edge"

      - name: Lint
        run: pnpm lint --filter="@plank/adapter-edge"

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Test Edge adapter with Wrangler
        run: |
          echo "Testing Edge adapter with actual Cloudflare Workers runtime..."
          cd packages/adapters/edge

          # Test that the adapter can be deployed to Workers
          wrangler deploy --dry-run --compatibility-date=2024-01-01

          # Test that the adapter loads in Workers environment
          echo "Testing adapter loading in Workers environment..."
          node -e "
            // Simulate Workers environment
            global.KVNamespace = class MockKV {};
            global.R2Bucket = class MockR2 {};
            global.ExecutionContext = class MockExecutionContext {};

            const adapter = require('./dist/index.js');
            console.log('✅ Edge adapter loads successfully in Workers environment');
            console.log('Available exports:', Object.keys(adapter));
            console.log('createEdgeAdapter type:', typeof adapter.createEdgeAdapter);

            // Test that we can create an adapter instance
            try {
              const testAdapter = adapter.createEdgeAdapter({
                staticAssets: {
                  kvNamespace: new global.KVNamespace(),
                  r2Bucket: new global.R2Bucket()
                }
              });
              console.log('✅ Can create Edge adapter instance');
              console.log('Adapter type:', typeof testAdapter);
            } catch (error) {
              console.log('⚠️  Adapter creation test:', error.message);
            }
          "

      - name: Run Edge integration tests
        run: cd packages/adapters/edge && node test-edge.test.js

  # Deno Adapter Tests
  deno-adapter:
    name: Deno Adapter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.40, latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build --filter="@plank/adapter-deno"

      - name: Run unit tests
        run: pnpm test --filter="@plank/adapter-deno"

      - name: Type check
        run: pnpm type-check --filter="@plank/adapter-deno"

      - name: Lint
        run: pnpm lint --filter="@plank/adapter-deno"

      - name: Test Deno runtime compatibility
        run: |
          echo "Testing Deno adapter with actual Deno runtime..."
          deno run --allow-net --allow-read packages/adapters/deno/scripts/compat.ts

      - name: Run Deno integration tests
        run: cd packages/adapters/deno && deno test --allow-net --allow-read test-deno.test.js

  # Cross-runtime compatibility tests
  cross-runtime:
    name: Cross-Runtime Compatibility
    runs-on: ubuntu-latest
    needs: [node-adapter, bun-adapter, edge-adapter, deno-adapter]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all adapters
        run: pnpm build --filter="@plank/adapter-*"

      - name: Test adapter exports
        run: |
          echo "Testing adapter exports..."
          node -e "
            const nodeAdapter = require('./packages/adapters/node/dist/index.js');
            const bunAdapter = require('./packages/adapters/bun/dist/index.js');
            const edgeAdapter = require('./packages/adapters/edge/dist/index.js');
            const denoAdapter = require('./packages/adapters/deno/dist/index.js');

            console.log('✅ All adapters built successfully');
            console.log('Node adapter:', typeof nodeAdapter.createNodeAdapter);
            console.log('Bun adapter:', typeof bunAdapter.createBunAdapter);
            console.log('Edge adapter:', typeof edgeAdapter.createEdgeAdapter);
            console.log('Deno adapter:', typeof denoAdapter.createDenoAdapter);
          "

      - name: Run full test suite
        run: pnpm test --filter="@plank/adapter-*"

  # Performance benchmarks
  benchmarks:
    name: Adapter Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build --filter="@plank/adapter-*"

      - name: Run benchmarks
        run: |
          echo "Running adapter benchmarks..."
          # Node adapter benchmarks
          cd packages/adapters/node && pnpm test:bench 2>/dev/null || echo "No benchmarks configured"

          # Bun adapter benchmarks
          cd ../bun && pnpm test:bench 2>/dev/null || echo "No benchmarks configured"

          # Deno adapter benchmarks
          cd ../deno && pnpm test:bench 2>/dev/null || echo "No benchmarks configured"
        continue-on-error: true

  # Security audit
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run security audit
        run: pnpm audit --audit-level moderate

      - name: Check for known vulnerabilities
        run: |
          echo "Checking adapter packages for vulnerabilities..."
          pnpm audit --filter="@plank/adapter-*" --audit-level moderate
